FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

COPY package.json ./
COPY apps/api/package.json ./apps/api/
COPY packages/shared/package.json ./packages/shared/
COPY db/prisma ./db/prisma

RUN npm install --workspaces --include-workspace-root
RUN cd apps/api && npx prisma generate

COPY apps/api/src ./apps/api/src
COPY packages/shared/src ./packages/shared/src
